title: AerialRAN
description: Documentation for Setting up CUDA Accelerated ORAN Deployment
theme: just-the-docs

url: https://cheddarhub.github.io/aerialran

# See: https://just-the-docs.github.io/just-the-docs/docs/configuration/#callouts
# See: https://just-the-docs.github.io/just-the-docs/docs/ui-components/callouts/
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  tip:
    title: Tip
    color: green
  note:
    title: Note
    color: purple
  information:
    title: Information
    color: yellow
  warning:
    title: Warning
    color: red
